#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Contributors To The `net.splitcells.*` Projects
# Use apt-get instead of apt, because apt recommands it that way: https://askubuntu.com/questions/990823/apt-gives-unstable-cli-interface-warning/990838#990838
if [ -x "$(command -v apt)" ]; then
	sudo apt-get install -y $1
else
	echo Apt is not installed.
	exit 1
fi
